config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:create, :index, :show, :new] do
    resources :reviews, only: [:new, :create, :index]
  end
  root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, numericality: { only_integer: true }
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_restaurant
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>

<i class="fas fa-plus"></i>
<%= link_to 'Add a new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number%>
  <%= f.text_field :phone_number%>
  <%= f.label :category%>
  <%= f.text_field :category%>
  <%= f.submit %>
<% end %>

<i class="fas fa-pen"></i>
<%= link_to 'Back to list', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Address: <%= @restaurant.address %></p>
<p>Phone Number: <%= @restaurant.phone_number %></p>
<p>Category: <%= @restaurant.category %></p>

<p>Reviews: </p>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      Rating: <%= review.rating %>
      <%= review.content %>
    </li>
  <% end %>
</ul>

<%= link_to 'Create a new review', new_restaurant_review_path(@restaurant) %>

<i class="fas fa-undo"></i>
<%= link_to 'Back to list', restaurants_path %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f|%>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

<i class="fas fa-pen"></i>
<%= link_to 'Back to list', restaurant_path(@restaurant) %>